[workspace]
resolver = "2"
members = [
  "engine_core",
  "engine_platform",
  "engine_render_api",
  "backend_vulkan",
  "backend_dx12",
  "backend_dx11",
  "engine_nodes",
  "engine_assets",
  "engine_audio",
  "engine_physics",
  "engine_editor",
  "engine_editor_app",
  "engine_app",
]

[workspace.package]
edition = "2021"
license = "AGPL-3.0-or-later"
version = "0.1.0"

[workspace.dependencies]
ash = "0.38"
ash-window = "0.13"
bevy_ecs = "0.17"
eframe = "0.33"
egui = "0.33"
egui-snarl = { version = "0.9", features = ["serde"] }
kira = "0.10"
raw-window-handle = "0.6"
rapier2d = "0.30"
rhai = "1.20"
ron = "0.11"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
sha2 = "0.10"
thiserror = "2"
tracing = "0.1"
winit = "0.30"
windows = { version = "0.62", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Graphics_Direct3D",
  "Win32_Graphics_Direct3D11",
  "Win32_Graphics_Direct3D12",
  "Win32_Graphics_Dxgi",
  "Win32_Graphics_Dxgi_Common",
  "Win32_System_Threading",
] }
