[package]
name = "engine_app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bevy_ecs.workspace = true
egui.workspace = true
engine_assets = { path = "../engine_assets" }
engine_audio = { path = "../engine_audio" }
engine_core = { path = "../engine_core" }
engine_editor = { path = "../engine_editor" }
engine_nodes = { path = "../engine_nodes" }
engine_physics = { path = "../engine_physics" }
engine_platform = { path = "../engine_platform" }
engine_render_api = { path = "../engine_render_api" }
backend_dx11 = { path = "../backend_dx11" }
backend_dx12 = { path = "../backend_dx12" }
backend_vulkan = { path = "../backend_vulkan" }
ron.workspace = true
thiserror.workspace = true
tracing.workspace = true
winit.workspace = true
