[package]
name = "backend_dx12"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
engine_core = { path = "../engine_core" }
engine_render_api = { path = "../engine_render_api" }
raw-window-handle.workspace = true
tracing.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true
